---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webapp-gcr-d3
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp-gcr-d3-lbl
    spec:
      containers:
      - name: c3-webapp-gcr
        image: gcr.io/k8-sunil/webserver:tagversion
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-gcr-svc3
spec:
  selector:
    app: webapp-gcr-d3-lbl
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
