---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webapp-d2
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp-d2-lbl
    spec:
      containers:
      - name: c1-webapp
        image: sunhil2007/webserver:tagversion
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-svc2
spec:
  selector:
    app: webapp-d2-lbl
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
